# Generated by Django 6.0.5 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='promt',
            name='slug',
            field=models.SlugField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promt',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
